services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: polymarket-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - polymarket_db:/app?polymarket.db
    ports:
      - "8000:8000"
    networks:
      - pnet
    depends_on:
      - qdrant

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: polymarket-frontend:latest
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - pnet

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - pnet

volumes:
  polymarket_db:
  qdrant_data:

networks:
  pnet:
    driver: bridge
